// GERADO por scripts/gerar_dados_webgame.py — nao editar a mao.
const CARTAS = [
  {
    "nome": "Rei Arthur",
    "arquivo": "../cards/Rei_Arthur.png",
    "tipo": "Herói",
    "elemento": "Vento",
    "custoMana": 3,
    "resistencia": 16,
    "combate": 18,
    "efeito": "Habilidade (uma vez por turno) — Excalibur: ganha +4 de Combate neste turno.",
    "custoHabilidade": 1
  },
  {
    "nome": "Beowulf",
    "arquivo": "../cards/Beowulf.png",
    "tipo": "Herói",
    "elemento": "Terra",
    "custoMana": 2,
    "resistencia": 18,
    "combate": 16,
    "efeito": "Habilidade (uma vez por turno) — Vigor: recupera 4 pontos de Resistência (sem passar do valor impresso na carta).",
    "custoHabilidade": 1
  },
  {
    "nome": "Odisseu",
    "arquivo": "../cards/Odisseu.png",
    "tipo": "Herói",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": 14,
    "combate": 14,
    "efeito": "Habilidade (uma vez por turno) — Astúcia: a próxima Maldição que o oponente ativar contra você é anulada.",
    "custoHabilidade": 2
  },
  {
    "nome": "Sigurd",
    "arquivo": "../cards/Sigurd.png",
    "tipo": "Herói",
    "elemento": "Vento",
    "custoMana": 3,
    "resistencia": 15,
    "combate": 17,
    "efeito": "Habilidade (uma vez por turno) — Matador de Feras: prepara um bônus que, se você atacar um Monstro antes do fim deste turno, dobra o dano desse ataque.",
    "custoHabilidade": 2
  },
  {
    "nome": "Joana d'Arc",
    "arquivo": "../cards/Joana_d'Arc.png",
    "tipo": "Herói",
    "elemento": "Fogo",
    "custoMana": 4,
    "resistencia": 17,
    "combate": 12,
    "efeito": "Habilidade (uma vez por turno) — Milagre: cura totalmente o seu combatente em campo (sem passar do valor impresso na carta).",
    "custoHabilidade": 3
  },
  {
    "nome": "Gilgamesh",
    "arquivo": "../cards/Gilgamesh.png",
    "tipo": "Herói",
    "elemento": "Terra",
    "custoMana": 3,
    "resistencia": 19,
    "combate": 15,
    "efeito": "Habilidade (uma vez por turno) — Tesouro: compre 1 carta do Baralho Arcano.",
    "custoHabilidade": 1
  },
  {
    "nome": "Aquiles",
    "arquivo": "../cards/Aquiles.png",
    "tipo": "Herói",
    "elemento": "Vento",
    "custoMana": 2,
    "resistencia": 15,
    "combate": 19,
    "efeito": "Habilidade (uma vez por turno) — Rapidez: ataca duas vezes o combatente ativo do oponente (ou o feiticeiro, se não houver), cada ataque com o dano final reduzido à metade. Conta como o seu ataque do turno.",
    "custoHabilidade": 2
  },
  {
    "nome": "Atalanta",
    "arquivo": "../cards/Atalanta.png",
    "tipo": "Herói",
    "elemento": "Vento",
    "custoMana": 2,
    "resistencia": 12,
    "combate": 16,
    "efeito": "Habilidade (uma vez por turno) — Flecha Veloz: causa 5 de dano direto aos Pontos de Vida do feiticeiro oponente, ignorando combate.",
    "custoHabilidade": 2
  },
  {
    "nome": "Cu Chulainn",
    "arquivo": "../cards/Cu_Chulainn.png",
    "tipo": "Herói",
    "elemento": "Terra",
    "custoMana": 3,
    "resistencia": 16,
    "combate": 17,
    "efeito": "Habilidade (uma vez por turno) — Fúria Final: até o fim deste turno, se este combatente for derrotado atacando (por reflexo de dano), o combatente ativo do oponente também é destruído.",
    "custoHabilidade": 1
  },
  {
    "nome": "Merlin",
    "arquivo": "../cards/Merlin.png",
    "tipo": "Herói",
    "elemento": "Água",
    "custoMana": 1,
    "resistencia": 10,
    "combate": 10,
    "efeito": "Habilidade (uma vez por turno) — Clarividência: olhe as 3 cartas do topo do seu Baralho Arcano, sem alterar a ordem.",
    "custoHabilidade": 1
  },
  {
    "nome": "Cthulhu",
    "arquivo": "../cards/Cthulhu.png",
    "tipo": "Monstro",
    "elemento": "Água",
    "custoMana": 4,
    "resistencia": 20,
    "combate": 16,
    "efeito": "Habilidade (uma vez por turno) — Loucura: o oponente descarta 2 cartas aleatórias da mão.",
    "custoHabilidade": 2
  },
  {
    "nome": "Fenrir",
    "arquivo": "../cards/Fenrir.png",
    "tipo": "Monstro",
    "elemento": "Fogo",
    "custoMana": 3,
    "resistencia": 18,
    "combate": 19,
    "efeito": "Habilidade (uma vez por turno) — Devorar: destrói a carta de Domínio ativa no campo, seja de quem for.",
    "custoHabilidade": 2
  },
  {
    "nome": "Jörmungandr",
    "arquivo": "../cards/Jörmungandr.png",
    "tipo": "Monstro",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": 19,
    "combate": 15,
    "efeito": "Habilidade (uma vez por turno) — Veneno: causa 3 de dano ao combatente ativo do oponente agora, e mais 3 de dano no início de cada turno do dono dele, até esse combatente ser destruído.",
    "custoHabilidade": 2
  },
  {
    "nome": "Tífon",
    "arquivo": "../cards/Tífon.png",
    "tipo": "Monstro",
    "elemento": "Vento",
    "custoMana": 4,
    "resistencia": 17,
    "combate": 18,
    "efeito": "Habilidade (uma vez por turno) — Tempestade: retorna o combatente ativo do oponente para o Panteão dele.",
    "custoHabilidade": 3
  },
  {
    "nome": "Shoggoth",
    "arquivo": "../cards/Shoggoth.png",
    "tipo": "Monstro",
    "elemento": "Terra",
    "custoMana": 2,
    "resistencia": 19,
    "combate": 12,
    "efeito": "Habilidade (uma vez por turno) — Disforme: até o fim deste turno, você ignora a vantagem elemental do oponente contra este combatente.",
    "custoHabilidade": 1
  },
  {
    "nome": "Surtur",
    "arquivo": "../cards/Surtur.png",
    "tipo": "Monstro",
    "elemento": "Fogo",
    "custoMana": 5,
    "resistencia": 16,
    "combate": 20,
    "efeito": "Habilidade (uma vez por turno) — Ragnarok: causa 10 de dano a todos os combatentes ativos em campo, incluindo o seu.",
    "custoHabilidade": 3
  },
  {
    "nome": "Wendigo",
    "arquivo": "../cards/Wendigo.png",
    "tipo": "Monstro",
    "elemento": "Vento",
    "custoMana": 2,
    "resistencia": 14,
    "combate": 16,
    "efeito": "Habilidade (uma vez por turno) — Fome: rouba até 2 de Mana da reserva do oponente (limitado ao que ele tiver) e adiciona à sua.",
    "custoHabilidade": 1
  },
  {
    "nome": "Nyarlathotep",
    "arquivo": "../cards/Nyarlathotep.png",
    "tipo": "Monstro",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": 15,
    "combate": 14,
    "efeito": "Habilidade (uma vez por turno) — Caos: revele as Maldições viradas para baixo do oponente e escolha uma para destruir.",
    "custoHabilidade": 2
  },
  {
    "nome": "Minotauro",
    "arquivo": "../cards/Minotauro.png",
    "tipo": "Monstro",
    "elemento": "Terra",
    "custoMana": 2,
    "resistencia": 18,
    "combate": 15,
    "efeito": "Habilidade (uma vez por turno) — Labirinto: impede o combatente ativo do oponente de usar a própria Habilidade neste turno (a menos que ele seja imune).",
    "custoHabilidade": 2
  },
  {
    "nome": "Quimera",
    "arquivo": "../cards/Quimera.png",
    "tipo": "Monstro",
    "elemento": "Fogo",
    "custoMana": 2,
    "resistencia": 16,
    "combate": 17,
    "efeito": "Habilidade (uma vez por turno) — Três Cabeças: ganha +2 de Combate neste turno se o combatente ativo do oponente for do elemento Terra.",
    "custoHabilidade": 1
  },
  {
    "nome": "Trono de Camelot",
    "arquivo": "../cards/Trono_de_Camelot.png",
    "tipo": "Domínio",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Passivo (sem ativação, enquanto este Domínio estiver ativo): todo Herói em campo, de qualquer lado, ganha +3 de Combate. Gatilho — quando este Domínio for destruído: o dono dele compra 1 carta.",
    "custoHabilidade": null
  },
  {
    "nome": "Fenda de R'lyeh",
    "arquivo": "../cards/Fenda_de_R'lyeh.png",
    "tipo": "Domínio",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Passivo (sem ativação, enquanto este Domínio estiver ativo): todo Monstro em campo, de qualquer lado, ganha +4 de Resistência (lembrete: o teto de 20 pontos vale só pro valor impresso na carta — habilidades e efeitos sempre podem passar disso, em qualquer carta do jogo). Gatilho — no início de qualquer turno: os dois feiticeiros descartam 1 carta aleatória da mão.",
    "custoHabilidade": null
  },
  {
    "nome": "Vulcão Primordial",
    "arquivo": "../cards/Vulcão_Primordial.png",
    "tipo": "Domínio",
    "elemento": "Fogo",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Passivo (sem ativação, enquanto este Domínio estiver ativo): todo combatente de Fogo em campo, de qualquer lado, ganha +3 de Combate; todo combatente de Vento em campo, de qualquer lado, perde -2 de Resistência.",
    "custoHabilidade": null
  },
  {
    "nome": "Templo de Atlântida",
    "arquivo": "../cards/Templo_de_Atlântida.png",
    "tipo": "Domínio",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Gatilho (sem efeito passivo) — sempre que um combatente de Água, de qualquer lado, usar sua Habilidade: o dono desse combatente recupera 1 de Mana.",
    "custoHabilidade": null
  },
  {
    "nome": "Cânion dos Ventos",
    "arquivo": "../cards/Cânion_dos_Ventos.png",
    "tipo": "Domínio",
    "elemento": "Vento",
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Gatilho (sem efeito passivo) — sempre que um combatente de Vento atacar e sobreviver: ele retorna automaticamente para o Panteão do dono logo em seguida (não é uma escolha).",
    "custoHabilidade": null
  },
  {
    "nome": "Jardins Suspensos",
    "arquivo": "../cards/Jardins_Suspensos.png",
    "tipo": "Domínio",
    "elemento": "Terra",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Passivo (sem ativação, enquanto este Domínio estiver ativo): todo dano recebido por um combatente de Terra, de qualquer lado, é reduzido em 3. Gatilho — quando um combatente de Terra for destruído: o dono DESTE DOMÍNIO (não necessariamente o dono do combatente) ganha 4 de Mana.",
    "custoHabilidade": null
  },
  {
    "nome": "Tomo do Oráculo",
    "arquivo": "../cards/Tomo_do_Oráculo.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): compre 2 cartas do seu Baralho Arcano.",
    "custoHabilidade": null
  },
  {
    "nome": "Pacto de Sangue",
    "arquivo": "../cards/Pacto_de_Sangue.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 1,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): seu combatente ativo perde 5 de Resistência (podendo ser destruído, se isso zerar a Resistência dele); se sobreviver, ganha +6 de Combate até o fim do turno.",
    "custoHabilidade": null
  },
  {
    "nome": "Visão do Olho Que Tudo Vê",
    "arquivo": "../cards/Visão_do_Olho_Que_Tudo_Vê.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): o oponente revela a mão dele; escolha 1 carta de Maldição ou Encantamento de lá e descarte.",
    "custoHabilidade": null
  },
  {
    "nome": "Ressurreição Arcana",
    "arquivo": "../cards/Ressurreição_Arcana.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): escolha 1 carta da sua própria Pilha de Descarte e coloque-a na sua mão. (Bloqueado enquanto Fosso de Tártaro estiver ativo.)",
    "custoHabilidade": null
  },
  {
    "nome": "Transmutação Elemental",
    "arquivo": "../cards/Transmutação_Elemental.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): escolha uma Natureza Elemental diferente da atual para o seu combatente ativo; vale até o início do seu próximo turno.",
    "custoHabilidade": null
  },
  {
    "nome": "Desintegração de Realidade",
    "arquivo": "../cards/Desintegração_de_Realidade.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): destrua a carta de Domínio ativa no campo, seja de quem for. (A parte sobre Equipamento não se aplica — esse subtipo não existe neste baralho.)",
    "custoHabilidade": null
  },
  {
    "nome": "Vórtice Dimensional",
    "arquivo": "../cards/Vórtice_Dimensional.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): retorne o combatente ativo do oponente para o Panteão dele.",
    "custoHabilidade": null
  },
  {
    "nome": "Valhalla",
    "arquivo": "../cards/Valhalla.png",
    "tipo": "Domínio",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Gatilho (sem efeito passivo) — quando um Herói for derrotado, de qualquer lado: ele retorna para o Panteão do dono dele em vez de ir para a Pilha de Descarte.",
    "custoHabilidade": null
  },
  {
    "nome": "Fosso de Tártaro",
    "arquivo": "../cards/Fosso_de_Tártaro.png",
    "tipo": "Domínio",
    "elemento": "Terra",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Passivo (sem ativação, enquanto este Domínio estiver ativo): todo Monstro em campo, de qualquer lado, ganha +3 de Combate; nenhuma carta pode ser recuperada da Pilha de Descarte (bloqueia Ressurreição Arcana e Chamado do Além).",
    "custoHabilidade": null
  },
  {
    "nome": "Oceano Primordial",
    "arquivo": "../cards/Oceano_Primordial.png",
    "tipo": "Domínio",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Gatilho (sem efeito passivo) — no início do turno de cada jogador: revela a carta do topo do próprio Baralho Arcano; se for do elemento Água ou do tipo Encantamento, ele a compra de graça.",
    "custoHabilidade": null
  },
  {
    "nome": "Céus de Valíria",
    "arquivo": "../cards/Céus_de_Valíria.png",
    "tipo": "Domínio",
    "elemento": "Fogo/Vento",
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Passivo (sem ativação, enquanto este Domínio estiver ativo): todo Herói de Fogo ou Vento em campo, de qualquer lado, ignora desvantagem elemental. Gatilho — sempre que um desses Heróis atacar: o oponente dele descarta a carta do topo do próprio Baralho Arcano.",
    "custoHabilidade": null
  },
  {
    "nome": "Clarividência Divina",
    "arquivo": "../cards/Clarividência_Divina.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): revele as 3 cartas do topo do Baralho Arcano do oponente; escolha 1 para descartar e deixe as outras 2 no topo, na mesma ordem.",
    "custoHabilidade": null
  },
  {
    "nome": "Bênção de Yggdrasil",
    "arquivo": "../cards/Bênção_de_Yggdrasil.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): compre 2 cartas do seu Baralho Arcano; se, depois disso, sua mão tiver 1 carta ou menos, compre mais 1.",
    "custoHabilidade": null
  },
  {
    "nome": "Fúria Titânica",
    "arquivo": "../cards/Fúria_Titânica.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): seu combatente ativo ganha +8 de Combate neste turno; na Fase Final deste mesmo turno, ele sofre -4 de Resistência permanente.",
    "custoHabilidade": null
  },
  {
    "nome": "Troca Equivalente",
    "arquivo": "../cards/Troca_Equivalente.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 1,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): escolha até 3 cartas da sua mão para embaralhar de volta no Baralho Arcano; compre a mesma quantidade em seguida.",
    "custoHabilidade": null
  },
  {
    "nome": "Exílio Dimensional",
    "arquivo": "../cards/Exílio_Dimensional.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 5,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): envie o combatente ativo do oponente direto para a Pilha de Descarte dele; em seguida, ele invoca outro combatente do Panteão sem pagar o Custo de Mana.",
    "custoHabilidade": null
  },
  {
    "nome": "Chamado do Além",
    "arquivo": "../cards/Chamado_do_Além.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): escolha 1 Maldição da sua própria Pilha de Descarte e coloque-a na sua mão (simplificado: vai pra mão, não direto pro campo — mas setar uma Maldição já é grátis, então o efeito prático é quase o mesmo). (Bloqueado enquanto Fosso de Tártaro estiver ativo.)",
    "custoHabilidade": null
  },
  {
    "nome": "Purificação Arcana",
    "arquivo": "../cards/Purificação_Arcana.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): revele as Maldições viradas para baixo do oponente; escolha até 2 delas para destruir, uma de cada vez.",
    "custoHabilidade": null
  },
  {
    "nome": "Manto da Natureza",
    "arquivo": "../cards/Manto_da_Natureza.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao jogar (efeito único e imediato): seu combatente ativo ganha +5 de Resistência permanente e passa a ser imune a efeitos inimigos que bloqueiam ou cancelam a Habilidade dele (Minotauro, Amnésia Mágica, Roubo de Essência) enquanto continuar em campo.",
    "custoHabilidade": null
  },
  {
    "nome": "Escudo de Gelo Absoluto",
    "arquivo": "../cards/Escudo_de_Gelo_Absoluto.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando você for atacado, pode revelar isto (pagando o Custo de Mana): o ataque é completamente anulado e o combatente atacante perde a Natureza Elemental (fica sem elemento) até o fim do turno.",
    "custoHabilidade": null
  },
  {
    "nome": "Espelho das Ilusões",
    "arquivo": "../cards/Espelho_das_Ilusões.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando você for atacado, pode revelar isto (pagando o Custo de Mana): o dano deste combate é redirecionado para o atacante em vez de atingir o seu combatente.",
    "custoHabilidade": null
  },
  {
    "nome": "Areias Movediças",
    "arquivo": "../cards/Areias_Movediças.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando o oponente invocar um combatente, pode revelar isto (pagando o Custo de Mana): esse combatente entra em campo com -5 de Resistência permanente.",
    "custoHabilidade": null
  },
  {
    "nome": "Roubo de Essência",
    "arquivo": "../cards/Roubo_de_Essência.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando o oponente ativar uma Habilidade, pode revelar isto (pagando o Custo de Mana): roube a Mana que ele gastou (o efeito da Habilidade dele ainda acontece — esta versão simplificada não cancela, só rouba o custo). Não funciona contra um combatente imune (Manto da Natureza).",
    "custoHabilidade": null
  },
  {
    "nome": "Praga da Ferrugem",
    "arquivo": "../cards/Praga_da_Ferrugem.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 1,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando o oponente jogar um Equipamento, pode revelar isto (pagando o Custo de Mana): destrua-o antes do efeito e ele perde 1 de Mana. (Não implementado nesta versão — não existe subtipo Equipamento neste baralho; esta carta só pode ser destruída por outro efeito, como Purificação Arcana.)",
    "custoHabilidade": null
  },
  {
    "nome": "Vínculo Sombrio",
    "arquivo": "../cards/Vínculo_Sombrio.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando você for atacado, pode revelar isto (pagando o Custo de Mana): o Combate do atacante é ajustado para exatamente 10 até o fim do turno.",
    "custoHabilidade": null
  },
  {
    "nome": "Nevoeiro do Pânico",
    "arquivo": "../cards/Nevoeiro_do_Pânico.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando o oponente comprar a carta automática da Fase de Saque, pode revelar isto (pagando o Custo de Mana): ele descarta essa carta e compra a carta do fundo do próprio Baralho Arcano.",
    "custoHabilidade": null
  },
  {
    "nome": "Barreira de Vento Cortante",
    "arquivo": "../cards/Barreira_de_Vento_Cortante.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando você for atacado, pode revelar isto (pagando o Custo de Mana): o ataque é negado e o combatente atacante retorna para o Panteão do dono dele.",
    "custoHabilidade": null
  },
  {
    "nome": "Retribuição Kármica",
    "arquivo": "../cards/Retribuição_Kármica.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando você for atacado, pode revelar isto (pagando o Custo de Mana): o dano deste combate é redirecionado para o atacante em vez de atingir o seu combatente.",
    "custoHabilidade": null
  },
  {
    "nome": "Aperto da Múmia",
    "arquivo": "../cards/Aperto_da_Múmia.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando o oponente invocar um combatente, pode revelar isto (pagando o Custo de Mana): esse combatente entra em campo com -5 de Resistência e -3 de Combate, permanentemente.",
    "custoHabilidade": null
  },
  {
    "nome": "Mente Fraturada",
    "arquivo": "../cards/Mente_Fraturada.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando o oponente comprar carta por um efeito de outra carta (não a compra automática do turno), pode revelar isto (pagando o Custo de Mana): ele descarta a carta de maior Custo de Mana da própria mão.",
    "custoHabilidade": null
  },
  {
    "nome": "Amnésia Mágica",
    "arquivo": "../cards/Amnésia_Mágica.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando o oponente ativar uma Habilidade, pode revelar isto (pagando o Custo de Mana): o combatente dele fica impedido de usar a Habilidade de novo neste turno (o efeito já ativado ainda acontece — esta versão simplificada não desfaz o que já rodou). Não funciona contra um combatente imune (Manto da Natureza).",
    "custoHabilidade": null
  },
  {
    "nome": "Fio do Destino Cortado",
    "arquivo": "../cards/Fio_do_Destino_Cortado.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando o oponente ativar uma Habilidade, pode revelar isto (pagando o Custo de Mana): inverte o sinal de todos os bônus/penalidades de Combate e Resistência atualmente ativos no combatente dele (ex.: +4 vira -4). Aproximação: dispara na ativação de qualquer Habilidade, não só quando ela concede um buff específico.",
    "custoHabilidade": null
  },
  {
    "nome": "Rebote Arcano",
    "arquivo": "../cards/Rebote_Arcano.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Redireciona o próximo feitiço do oponente para o combatente dele próprio. (Não implementado nesta versão — exigiria rastrear \"o próximo feitiço inimigo\" antes de ele resolver; revelar esta carta não tem efeito nenhum no jogo atual.)",
    "custoHabilidade": null
  },
  {
    "nome": "Caixa de Pandora",
    "arquivo": "../cards/Caixa_de_Pandora.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 1,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando você tiver um Domínio ou Combatente destruído, pode revelar isto (pagando o Custo de Mana): o oponente descarta 3 cartas aleatórias da própria mão.",
    "custoHabilidade": null
  },
  {
    "nome": "Apoio Incondicional",
    "arquivo": "../cards/Apoio_Incondicional.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Escolha o seu Combatente em campo e 1 no Panteão. Se um deles for alvo de um ataque ou de um efeito de carta do oponente, você pode dividir o dano da batalha igualmente entre os dois. (Não implementado nesta versão do motor — exigiria um mecanismo de \"par de alvos vinculados\" à parte; jogar esta carta não tem efeito nenhum no jogo atual.)",
    "custoHabilidade": null
  }
];
