// GERADO por scripts/gerar_dados_webgame.py — nao editar a mao.
const CARTAS = [
  {
    "nome": "Rei Arthur",
    "arquivo": "../cards/Rei_Arthur.png",
    "tipo": "Herói",
    "elemento": "Vento",
    "custoMana": 3,
    "resistencia": 16,
    "combate": 18,
    "efeito": "Uma vez por turno ganha +4 de Combate neste turno.",
    "custoHabilidade": 1
  },
  {
    "nome": "Beowulf",
    "arquivo": "../cards/Beowulf.png",
    "tipo": "Herói",
    "elemento": "Terra",
    "custoMana": 2,
    "resistencia": 18,
    "combate": 16,
    "efeito": "Uma vez por turno recupera 4 pontos de Resistência.",
    "custoHabilidade": 1
  },
  {
    "nome": "Odisseu",
    "arquivo": "../cards/Odisseu.png",
    "tipo": "Herói",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": 14,
    "combate": 14,
    "efeito": "Uma vez por turno anula a próxima Maldição do oponente.",
    "custoHabilidade": 2
  },
  {
    "nome": "Sigurd",
    "arquivo": "../cards/Sigurd.png",
    "tipo": "Herói",
    "elemento": "Vento",
    "custoMana": 3,
    "resistencia": 15,
    "combate": 17,
    "efeito": "Uma vez por turno prepara um bônus: se atacar um Monstro antes do fim do turno, dobra o dano desse ataque.",
    "custoHabilidade": 2
  },
  {
    "nome": "Joana d'Arc",
    "arquivo": "../cards/Joana_d'Arc.png",
    "tipo": "Herói",
    "elemento": "Fogo",
    "custoMana": 4,
    "resistencia": 17,
    "combate": 12,
    "efeito": "Uma vez por turno cura totalmente o seu combatente em campo.",
    "custoHabilidade": 3
  },
  {
    "nome": "Gilgamesh",
    "arquivo": "../cards/Gilgamesh.png",
    "tipo": "Herói",
    "elemento": "Terra",
    "custoMana": 3,
    "resistencia": 19,
    "combate": 15,
    "efeito": "Uma vez por turno compra 1 carta do Baralho Arcano.",
    "custoHabilidade": 1
  },
  {
    "nome": "Aquiles",
    "arquivo": "../cards/Aquiles.png",
    "tipo": "Herói",
    "elemento": "Vento",
    "custoMana": 2,
    "resistencia": 15,
    "combate": 19,
    "efeito": "Uma vez por turno ataca duas vezes, com o dano de cada ataque reduzido à metade. Conta como o ataque do turno.",
    "custoHabilidade": 2
  },
  {
    "nome": "Atalanta",
    "arquivo": "../cards/Atalanta.png",
    "tipo": "Herói",
    "elemento": "Vento",
    "custoMana": 2,
    "resistencia": 12,
    "combate": 16,
    "efeito": "Uma vez por turno causa 5 de dano direto ao oponente, ignorando combate.",
    "custoHabilidade": 2
  },
  {
    "nome": "Cu Chulainn",
    "arquivo": "../cards/Cu_Chulainn.png",
    "tipo": "Herói",
    "elemento": "Terra",
    "custoMana": 3,
    "resistencia": 16,
    "combate": 17,
    "efeito": "Uma vez por turno: se for derrotado atacando antes do fim do turno, o combatente ativo do oponente também é destruído.",
    "custoHabilidade": 1
  },
  {
    "nome": "Merlin",
    "arquivo": "../cards/Merlin.png",
    "tipo": "Herói",
    "elemento": "Água",
    "custoMana": 1,
    "resistencia": 10,
    "combate": 10,
    "efeito": "Uma vez por turno olha as 3 cartas do topo do seu Baralho Arcano.",
    "custoHabilidade": 1
  },
  {
    "nome": "Cthulhu",
    "arquivo": "../cards/Cthulhu.png",
    "tipo": "Monstro",
    "elemento": "Água",
    "custoMana": 4,
    "resistencia": 20,
    "combate": 16,
    "efeito": "Uma vez por turno o oponente descarta 2 cartas aleatórias da mão.",
    "custoHabilidade": 2
  },
  {
    "nome": "Fenrir",
    "arquivo": "../cards/Fenrir.png",
    "tipo": "Monstro",
    "elemento": "Fogo",
    "custoMana": 3,
    "resistencia": 18,
    "combate": 19,
    "efeito": "Uma vez por turno destrói a carta de Domínio ativa no campo, seja de quem for.",
    "custoHabilidade": 2
  },
  {
    "nome": "Jörmungandr",
    "arquivo": "../cards/Jörmungandr.png",
    "tipo": "Monstro",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": 19,
    "combate": 15,
    "efeito": "Uma vez por turno causa 3 de dano ao combatente ativo do oponente, e mais 3 no início de cada turno do dono dele até ele ser destruído.",
    "custoHabilidade": 2
  },
  {
    "nome": "Tífon",
    "arquivo": "../cards/Tífon.png",
    "tipo": "Monstro",
    "elemento": "Vento",
    "custoMana": 4,
    "resistencia": 17,
    "combate": 18,
    "efeito": "Uma vez por turno retorna o combatente ativo do oponente para o Panteão dele.",
    "custoHabilidade": 3
  },
  {
    "nome": "Shoggoth",
    "arquivo": "../cards/Shoggoth.png",
    "tipo": "Monstro",
    "elemento": "Terra",
    "custoMana": 2,
    "resistencia": 19,
    "combate": 12,
    "efeito": "Uma vez por turno ignora a vantagem elemental do oponente contra este combatente até o fim do turno.",
    "custoHabilidade": 1
  },
  {
    "nome": "Surtur",
    "arquivo": "../cards/Surtur.png",
    "tipo": "Monstro",
    "elemento": "Fogo",
    "custoMana": 5,
    "resistencia": 16,
    "combate": 20,
    "efeito": "Uma vez por turno causa 10 de dano a todos os combatentes ativos em campo, incluindo o seu.",
    "custoHabilidade": 3
  },
  {
    "nome": "Wendigo",
    "arquivo": "../cards/Wendigo.png",
    "tipo": "Monstro",
    "elemento": "Vento",
    "custoMana": 2,
    "resistencia": 14,
    "combate": 16,
    "efeito": "Uma vez por turno rouba até 2 de Mana do oponente.",
    "custoHabilidade": 1
  },
  {
    "nome": "Nyarlathotep",
    "arquivo": "../cards/Nyarlathotep.png",
    "tipo": "Monstro",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": 15,
    "combate": 14,
    "efeito": "Uma vez por turno revela as Maldições viradas para baixo do oponente e destrói uma escolhida.",
    "custoHabilidade": 2
  },
  {
    "nome": "Minotauro",
    "arquivo": "../cards/Minotauro.png",
    "tipo": "Monstro",
    "elemento": "Terra",
    "custoMana": 2,
    "resistencia": 18,
    "combate": 15,
    "efeito": "Uma vez por turno impede o combatente ativo do oponente de usar a própria Habilidade neste turno.",
    "custoHabilidade": 2
  },
  {
    "nome": "Quimera",
    "arquivo": "../cards/Quimera.png",
    "tipo": "Monstro",
    "elemento": "Fogo",
    "custoMana": 2,
    "resistencia": 16,
    "combate": 17,
    "efeito": "Uma vez por turno ganha +2 de Combate neste turno se o combatente ativo do oponente for do elemento Terra.",
    "custoHabilidade": 1
  },
  {
    "nome": "Trono de Camelot",
    "arquivo": "../cards/Trono_de_Camelot.png",
    "tipo": "Domínio",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Enquanto ativo, todos os Heróis em campo ganham +3 de Combate. Quando este Domínio for destruído, o dono compra 1 carta.",
    "custoHabilidade": null
  },
  {
    "nome": "Fenda de R'lyeh",
    "arquivo": "../cards/Fenda_de_R'lyeh.png",
    "tipo": "Domínio",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Enquanto ativo, todos os Monstros em campo ganham +4 de Resistência. No início de cada turno, os dois jogadores descartam 1 carta aleatória da mão.",
    "custoHabilidade": null
  },
  {
    "nome": "Vulcão Primordial",
    "arquivo": "../cards/Vulcão_Primordial.png",
    "tipo": "Domínio",
    "elemento": "Fogo",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Enquanto ativo, combatentes de Fogo em campo ganham +3 de Combate; combatentes de Vento em campo perdem 2 de Resistência.",
    "custoHabilidade": null
  },
  {
    "nome": "Templo de Atlântida",
    "arquivo": "../cards/Templo_de_Atlântida.png",
    "tipo": "Domínio",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Sempre que um combatente de Água usar a Habilidade, o feiticeiro dono desse combatente recupera 1 de Mana.",
    "custoHabilidade": null
  },
  {
    "nome": "Cânion dos Ventos",
    "arquivo": "../cards/Cânion_dos_Ventos.png",
    "tipo": "Domínio",
    "elemento": "Vento",
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Sempre que um combatente de Vento atacar e sobreviver, ele retorna automaticamente para o Panteão do dono.",
    "custoHabilidade": null
  },
  {
    "nome": "Jardins Suspensos",
    "arquivo": "../cards/Jardins_Suspensos.png",
    "tipo": "Domínio",
    "elemento": "Terra",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Enquanto ativo, combatentes de Terra recebem 3 a menos de dano. Quando um combatente de Terra for destruído, o dono deste Domínio ganha 4 de Mana.",
    "custoHabilidade": null
  },
  {
    "nome": "Tomo do Oráculo",
    "arquivo": "../cards/Tomo_do_Oráculo.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Compre 2 cartas do Baralho Arcano.",
    "custoHabilidade": null
  },
  {
    "nome": "Pacto de Sangue",
    "arquivo": "../cards/Pacto_de_Sangue.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 1,
    "resistencia": null,
    "combate": null,
    "efeito": "Sacrifique 5 pontos de Resistência do seu combatente; se sobreviver, ganha +6 de Combate até o fim do turno.",
    "custoHabilidade": null
  },
  {
    "nome": "Visão do Olho Que Tudo Vê",
    "arquivo": "../cards/Visão_do_Olho_Que_Tudo_Vê.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "O oponente revela a mão. Escolha uma carta de Maldição ou Encantamento de lá e descarte.",
    "custoHabilidade": null
  },
  {
    "nome": "Ressurreição Arcana",
    "arquivo": "../cards/Ressurreição_Arcana.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Escolha uma carta da sua Pilha de Descarte e coloque na mão.",
    "custoHabilidade": null
  },
  {
    "nome": "Transmutação Elemental",
    "arquivo": "../cards/Transmutação_Elemental.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Escolha uma Natureza Elemental diferente da atual para o seu combatente, até o início do seu próximo turno.",
    "custoHabilidade": null
  },
  {
    "nome": "Desintegração de Realidade",
    "arquivo": "../cards/Desintegração_de_Realidade.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Destrua a carta de Domínio ativa no campo.",
    "custoHabilidade": null
  },
  {
    "nome": "Vórtice Dimensional",
    "arquivo": "../cards/Vórtice_Dimensional.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Retorne o combatente ativo do oponente para o Panteão dele.",
    "custoHabilidade": null
  },
  {
    "nome": "Valhalla",
    "arquivo": "../cards/Valhalla.png",
    "tipo": "Domínio",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando um Herói for derrotado, ele retorna para o Panteão do dono em vez da Pilha de Descarte.",
    "custoHabilidade": null
  },
  {
    "nome": "Fosso de Tártaro",
    "arquivo": "../cards/Fosso_de_Tártaro.png",
    "tipo": "Domínio",
    "elemento": "Terra",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Enquanto ativo, todo Monstro em campo ganha +3 de Combate. Nenhuma carta pode ser recuperada da Pilha de Descarte.",
    "custoHabilidade": null
  },
  {
    "nome": "Oceano Primordial",
    "arquivo": "../cards/Oceano_Primordial.png",
    "tipo": "Domínio",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "No início do turno, revela a carta do topo do próprio Baralho. Se for de Água ou Encantamento, compra de graça.",
    "custoHabilidade": null
  },
  {
    "nome": "Céus de Valíria",
    "arquivo": "../cards/Céus_de_Valíria.png",
    "tipo": "Domínio",
    "elemento": "Fogo/Vento",
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Heróis de Fogo ou Vento ignoram desvantagem elemental. Sempre que atacam, o oponente descarta o topo do baralho.",
    "custoHabilidade": null
  },
  {
    "nome": "Clarividência Divina",
    "arquivo": "../cards/Clarividência_Divina.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Revele as 3 cartas do topo do baralho do oponente. Descarte 1 e devolva as outras 2.",
    "custoHabilidade": null
  },
  {
    "nome": "Bênção de Yggdrasil",
    "arquivo": "../cards/Bênção_de_Yggdrasil.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Compre 2 cartas. Se ficar com 1 ou 0 na mão, compre mais 1.",
    "custoHabilidade": null
  },
  {
    "nome": "Fúria Titânica",
    "arquivo": "../cards/Fúria_Titânica.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Ganha +8 de Combate neste turno. Na Fase Final deste turno, sofre -4 de Resistência permanente.",
    "custoHabilidade": null
  },
  {
    "nome": "Troca Equivalente",
    "arquivo": "../cards/Troca_Equivalente.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 1,
    "resistencia": null,
    "combate": null,
    "efeito": "Escolha até 3 cartas da mão para embaralhar no baralho. Compre a mesma quantidade.",
    "custoHabilidade": null
  },
  {
    "nome": "Exílio Dimensional",
    "arquivo": "../cards/Exílio_Dimensional.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 5,
    "resistencia": null,
    "combate": null,
    "efeito": "Envie o combatente ativo do oponente para a Pilha de Descarte. Ele invoca outro de graça.",
    "custoHabilidade": null
  },
  {
    "nome": "Chamado do Além",
    "arquivo": "../cards/Chamado_do_Além.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Escolha uma Maldição da sua Pilha de Descarte e coloque na mão.",
    "custoHabilidade": null
  },
  {
    "nome": "Purificação Arcana",
    "arquivo": "../cards/Purificação_Arcana.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Revele as Maldições do oponente. Destrua até duas delas.",
    "custoHabilidade": null
  },
  {
    "nome": "Manto da Natureza",
    "arquivo": "../cards/Manto_da_Natureza.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "O combatente ganha +5 de Resistência permanente e imunidade a Habilidades de Mana inimigas.",
    "custoHabilidade": null
  },
  {
    "nome": "Escudo de Gelo Absoluto",
    "arquivo": "../cards/Escudo_de_Gelo_Absoluto.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "O ataque é completamente anulado e o atacante perde a Natureza Elemental até o fim do turno.",
    "custoHabilidade": null
  },
  {
    "nome": "Espelho das Ilusões",
    "arquivo": "../cards/Espelho_das_Ilusões.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "O dano deste combate é redirecionado para o atacante em vez de atingir o seu combatente.",
    "custoHabilidade": null
  },
  {
    "nome": "Areias Movediças",
    "arquivo": "../cards/Areias_Movediças.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "O combatente invocado pelo oponente entra em campo com -5 de Resistência permanente.",
    "custoHabilidade": null
  },
  {
    "nome": "Roubo de Essência",
    "arquivo": "../cards/Roubo_de_Essência.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando o oponente ativar uma Habilidade, roube a Mana gasta.",
    "custoHabilidade": null
  },
  {
    "nome": "Praga da Ferrugem",
    "arquivo": "../cards/Praga_da_Ferrugem.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 1,
    "resistencia": null,
    "combate": null,
    "efeito": "O Equipamento jogado é destruído antes do efeito. O oponente perde 1 de Mana. (Não implementado.)",
    "custoHabilidade": null
  },
  {
    "nome": "Vínculo Sombrio",
    "arquivo": "../cards/Vínculo_Sombrio.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "O Combate do atacante é reduzido para exatamente 10 até o fim do turno.",
    "custoHabilidade": null
  },
  {
    "nome": "Nevoeiro do Pânico",
    "arquivo": "../cards/Nevoeiro_do_Pânico.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "O oponente descarta a carta comprada no início do turno e compra a do fundo do baralho.",
    "custoHabilidade": null
  },
  {
    "nome": "Barreira de Vento Cortante",
    "arquivo": "../cards/Barreira_de_Vento_Cortante.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "O ataque é negado e o atacante retorna para o Panteão do dono.",
    "custoHabilidade": null
  },
  {
    "nome": "Retribuição Kármica",
    "arquivo": "../cards/Retribuição_Kármica.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "O dano deste combate é redirecionado para o atacante em vez de atingir o seu combatente.",
    "custoHabilidade": null
  },
  {
    "nome": "Aperto da Múmia",
    "arquivo": "../cards/Aperto_da_Múmia.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "O combatente invocado pelo oponente entra com -5 de Resistência e -3 de Combate, permanentemente.",
    "custoHabilidade": null
  },
  {
    "nome": "Mente Fraturada",
    "arquivo": "../cards/Mente_Fraturada.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando o oponente comprar carta por um efeito, ele descarta a carta de maior Custo de Mana da mão.",
    "custoHabilidade": null
  },
  {
    "nome": "Amnésia Mágica",
    "arquivo": "../cards/Amnésia_Mágica.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando o oponente ativar uma Habilidade, o combatente dele fica impedido de usar Habilidade de novo neste turno.",
    "custoHabilidade": null
  },
  {
    "nome": "Fio do Destino Cortado",
    "arquivo": "../cards/Fio_do_Destino_Cortado.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando o oponente ativar uma Habilidade, inverte o sinal dos bônus e penalidades ativos no combatente dele (ex: +4 vira -4).",
    "custoHabilidade": null
  },
  {
    "nome": "Rebote Arcano",
    "arquivo": "../cards/Rebote_Arcano.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Redireciona o próximo feitiço do oponente para o combatente dele. (Não implementado.)",
    "custoHabilidade": null
  },
  {
    "nome": "Caixa de Pandora",
    "arquivo": "../cards/Caixa_de_Pandora.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 1,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando você tiver um Domínio ou Combatente destruído, o oponente descarta 3 cartas aleatórias da mão.",
    "custoHabilidade": null
  },
  {
    "nome": "Apoio Incondicional",
    "arquivo": "../cards/Apoio_Incondicional.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Escolha o seu Combatente em campo e 1 no Panteão. Se um deles for alvo de um ataque ou de um efeito de carta do oponente, você pode dividir o dano da batalha igualmente entre os dois. (Não implementado.)",
    "custoHabilidade": null
  }
];
