// GERADO por scripts/gerar_dados_webgame.py — nao editar a mao.
const CARTAS = [
  {
    "nome": "Rei Arthur",
    "arquivo": "../cards/Rei_Arthur.png",
    "tipo": "Herói",
    "elemento": "Vento",
    "custoMana": 3,
    "resistencia": 16,
    "combate": 18,
    "efeito": "Excalibur: Ganha +4 de Combate neste turno.",
    "custoHabilidade": 1
  },
  {
    "nome": "Beowulf",
    "arquivo": "../cards/Beowulf.png",
    "tipo": "Herói",
    "elemento": "Terra",
    "custoMana": 2,
    "resistencia": 18,
    "combate": 16,
    "efeito": "Vigor: Recupera 4 pontos de Resistência.",
    "custoHabilidade": 1
  },
  {
    "nome": "Odisseu",
    "arquivo": "../cards/Odisseu.png",
    "tipo": "Herói",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": 14,
    "combate": 14,
    "efeito": "Astúcia: Anula a próxima Maldição do oponente.",
    "custoHabilidade": 2
  },
  {
    "nome": "Sigurd",
    "arquivo": "../cards/Sigurd.png",
    "tipo": "Herói",
    "elemento": "Vento",
    "custoMana": 3,
    "resistencia": 15,
    "combate": 17,
    "efeito": "Matador de Feras: Dano em dobro contra Monstros.",
    "custoHabilidade": 2
  },
  {
    "nome": "Joana d'Arc",
    "arquivo": "../cards/Joana_d'Arc.png",
    "tipo": "Herói",
    "elemento": "Fogo",
    "custoMana": 4,
    "resistencia": 17,
    "combate": 12,
    "efeito": "Milagre: Cura totalmente um aliado em campo.",
    "custoHabilidade": 3
  },
  {
    "nome": "Gilgamesh",
    "arquivo": "../cards/Gilgamesh.png",
    "tipo": "Herói",
    "elemento": "Terra",
    "custoMana": 3,
    "resistencia": 19,
    "combate": 15,
    "efeito": "Tesouro: Compre 1 carta de Equipamento do baralho.",
    "custoHabilidade": 1
  },
  {
    "nome": "Aquiles",
    "arquivo": "../cards/Aquiles.png",
    "tipo": "Herói",
    "elemento": "Vento",
    "custoMana": 2,
    "resistencia": 15,
    "combate": 19,
    "efeito": "Rapidez: Ataca duas vezes, mas o dano é reduzido à metade.",
    "custoHabilidade": 2
  },
  {
    "nome": "Atalanta",
    "arquivo": "../cards/Atalanta.png",
    "tipo": "Herói",
    "elemento": "Vento",
    "custoMana": 2,
    "resistencia": 12,
    "combate": 16,
    "efeito": "Flecha Veloz: Causa 5 de dano direto, ignorando combate.",
    "custoHabilidade": 2
  },
  {
    "nome": "Cu Chulainn",
    "arquivo": "../cards/Cu_Chulainn.png",
    "tipo": "Herói",
    "elemento": "Terra",
    "custoMana": 3,
    "resistencia": 16,
    "combate": 17,
    "efeito": "Fúria Final: Se for derrotado no ataque, o alvo também é.",
    "custoHabilidade": 1
  },
  {
    "nome": "Merlin",
    "arquivo": "../cards/Merlin.png",
    "tipo": "Herói",
    "elemento": "Água",
    "custoMana": 1,
    "resistencia": 10,
    "combate": 10,
    "efeito": "Clarividência: Olhe as 3 cartas do topo do Baralho Arcano.",
    "custoHabilidade": 1
  },
  {
    "nome": "Cthulhu",
    "arquivo": "../cards/Cthulhu.png",
    "tipo": "Monstro",
    "elemento": "Água",
    "custoMana": 4,
    "resistencia": 20,
    "combate": 16,
    "efeito": "Loucura: Oponente deve descartar 2 cartas da mão.",
    "custoHabilidade": 2
  },
  {
    "nome": "Fenrir",
    "arquivo": "../cards/Fenrir.png",
    "tipo": "Monstro",
    "elemento": "Fogo",
    "custoMana": 3,
    "resistencia": 18,
    "combate": 19,
    "efeito": "Devorar: Destrói a carta de Domínio ativa no campo.",
    "custoHabilidade": 2
  },
  {
    "nome": "Jörmungandr",
    "arquivo": "../cards/Jörmungandr.png",
    "tipo": "Monstro",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": 19,
    "combate": 15,
    "efeito": "Veneno: Causa 3 de dano por turno ao alvo atingido.",
    "custoHabilidade": 2
  },
  {
    "nome": "Tífon",
    "arquivo": "../cards/Tífon.png",
    "tipo": "Monstro",
    "elemento": "Vento",
    "custoMana": 4,
    "resistencia": 17,
    "combate": 18,
    "efeito": "Tempestade: Retorna 1 combatente inimigo para o Panteão.",
    "custoHabilidade": 3
  },
  {
    "nome": "Shoggoth",
    "arquivo": "../cards/Shoggoth.png",
    "tipo": "Monstro",
    "elemento": "Terra",
    "custoMana": 2,
    "resistencia": 19,
    "combate": 12,
    "efeito": "Disforme: Ignora fraqueza elemental até o fim do turno.",
    "custoHabilidade": 1
  },
  {
    "nome": "Surtur",
    "arquivo": "../cards/Surtur.png",
    "tipo": "Monstro",
    "elemento": "Fogo",
    "custoMana": 5,
    "resistencia": 16,
    "combate": 20,
    "efeito": "Ragnarok: Causa 10 de dano a todos os combatentes em campo.",
    "custoHabilidade": 3
  },
  {
    "nome": "Wendigo",
    "arquivo": "../cards/Wendigo.png",
    "tipo": "Monstro",
    "elemento": "Vento",
    "custoMana": 2,
    "resistencia": 14,
    "combate": 16,
    "efeito": "Fome: Rouba 2 pontos de Mana da reserva do oponente.",
    "custoHabilidade": 1
  },
  {
    "nome": "Nyarlathotep",
    "arquivo": "../cards/Nyarlathotep.png",
    "tipo": "Monstro",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": 15,
    "combate": 14,
    "efeito": "Caos: Olhe as Maldições ocultas do oponente e desarme uma.",
    "custoHabilidade": 2
  },
  {
    "nome": "Minotauro",
    "arquivo": "../cards/Minotauro.png",
    "tipo": "Monstro",
    "elemento": "Terra",
    "custoMana": 2,
    "resistencia": 18,
    "combate": 15,
    "efeito": "Labirinto: Impede o inimigo de usar Habilidades de Mana.",
    "custoHabilidade": 2
  },
  {
    "nome": "Quimera",
    "arquivo": "../cards/Quimera.png",
    "tipo": "Monstro",
    "elemento": "Fogo",
    "custoMana": 2,
    "resistencia": 16,
    "combate": 17,
    "efeito": "Três Cabeças: Ganha +2 de Combate se o alvo for do elemento Terra.",
    "custoHabilidade": 1
  },
  {
    "nome": "Trono de Camelot",
    "arquivo": "../cards/Trono_de_Camelot.png",
    "tipo": "Domínio",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Heróis: Enquanto ativo, todos os Espíritos Heróicos ganham +3 de Combate. Se o Domínio for destruído, o dono compra 1 carta.",
    "custoHabilidade": null
  },
  {
    "nome": "Fenda de R'lyeh",
    "arquivo": "../cards/Fenda_de_R'lyeh.png",
    "tipo": "Domínio",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Monstros: O limite máximo de atributos é ignorado. Monstros Primordiais ganham +4 de Resistência. No início do turno, ambos descartam 1 carta.",
    "custoHabilidade": null
  },
  {
    "nome": "Vulcão Primordial",
    "arquivo": "../cards/Vulcão_Primordial.png",
    "tipo": "Domínio",
    "elemento": "Fogo",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Natureza (Fogo): Combatentes de Fogo causam +3 de dano. Combatentes de Vento perdem -2 de Resistência.",
    "custoHabilidade": null
  },
  {
    "nome": "Templo de Atlântida",
    "arquivo": "../cards/Templo_de_Atlântida.png",
    "tipo": "Domínio",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Natureza (Água): Sempre que um combatente de Água usar uma Habilidade de Mana, o feiticeiro recupera 1 de Mana.",
    "custoHabilidade": null
  },
  {
    "nome": "Cânion dos Ventos",
    "arquivo": "../cards/Cânion_dos_Ventos.png",
    "tipo": "Domínio",
    "elemento": "Vento",
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Natureza (Vento): Combatentes de Vento podem retornar ao Panteão logo após atacar, evitando contra-ataques.",
    "custoHabilidade": null
  },
  {
    "nome": "Jardins Suspensos",
    "arquivo": "../cards/Jardins_Suspensos.png",
    "tipo": "Domínio",
    "elemento": "Terra",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Natureza (Terra): Todo dano recebido por combatentes de Terra é reduzido em 3. Se um for derrotado, o feiticeiro ganha 4 de Mana.",
    "custoHabilidade": null
  },
  {
    "nome": "Tomo do Oráculo",
    "arquivo": "../cards/Tomo_do_Oráculo.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Compre 2 cartas do Baralho Arcano.",
    "custoHabilidade": null
  },
  {
    "nome": "Pacto de Sangue",
    "arquivo": "../cards/Pacto_de_Sangue.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 1,
    "resistencia": null,
    "combate": null,
    "efeito": "Sacrifique 5 pontos da Resistência do seu combatente para lhe dar +6 de Combate até o fim do turno.",
    "custoHabilidade": null
  },
  {
    "nome": "Visão do Olho Que Tudo Vê",
    "arquivo": "../cards/Visão_do_Olho_Que_Tudo_Vê.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "O oponente deve revelar sua mão. Escolha uma carta de Maldição ou Encantamento de lá e envie para a Pilha de Descarte.",
    "custoHabilidade": null
  },
  {
    "nome": "Ressurreição Arcana",
    "arquivo": "../cards/Ressurreição_Arcana.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Escolha qualquer carta da sua Pilha de Descarte e coloque-a diretamente na sua mão.",
    "custoHabilidade": null
  },
  {
    "nome": "Transmutação Elemental",
    "arquivo": "../cards/Transmutação_Elemental.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Mude a Natureza Elemental do seu combatente ativo para qualquer outra até o início do seu próximo turno.",
    "custoHabilidade": null
  },
  {
    "nome": "Desintegração de Realidade",
    "arquivo": "../cards/Desintegração_de_Realidade.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Destrua a carta de Domínio ativa na mesa ou um Equipamento ligado a um combatente inimigo.",
    "custoHabilidade": null
  },
  {
    "nome": "Vórtice Dimensional",
    "arquivo": "../cards/Vórtice_Dimensional.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Retorne o combatente inimigo ativo de volta para o Panteão do oponente.",
    "custoHabilidade": null
  },
  {
    "nome": "Valhalla",
    "arquivo": "../cards/Valhalla.png",
    "tipo": "Domínio",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Quando um Espírito Heróico for derrotado, em vez de ir para a Pilha de Descarte, ele retorna para o Panteão.",
    "custoHabilidade": null
  },
  {
    "nome": "Fosso de Tártaro",
    "arquivo": "../cards/Fosso_de_Tártaro.png",
    "tipo": "Domínio",
    "elemento": "Terra",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Todo Monstro em campo ganha +3 de Combate. Nenhuma carta pode ser retirada ou revivida da Pilha de Descarte.",
    "custoHabilidade": null
  },
  {
    "nome": "Oceano Primordial",
    "arquivo": "../cards/Oceano_Primordial.png",
    "tipo": "Domínio",
    "elemento": "Água",
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "No início do turno, revela a carta do topo do Baralho. Se for de Água ou Encantamento, compra de graça.",
    "custoHabilidade": null
  },
  {
    "nome": "Céus de Valíria",
    "arquivo": "../cards/Céus_de_Valíria.png",
    "tipo": "Domínio",
    "elemento": "Fogo/Vento",
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Heróis de Fogo/Vento ignoram desvantagem elemental. Sempre que atacam, oponente descarta o topo do baralho.",
    "custoHabilidade": null
  },
  {
    "nome": "Clarividência Divina",
    "arquivo": "../cards/Clarividência_Divina.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Olhe as 3 cartas do topo do baralho inimigo. Descarte 1 e devolva as outras 2.",
    "custoHabilidade": null
  },
  {
    "nome": "Bênção de Yggdrasil",
    "arquivo": "../cards/Bênção_de_Yggdrasil.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Compre 2 cartas. Se tiver 1 ou 0 na mão, compre uma terceira.",
    "custoHabilidade": null
  },
  {
    "nome": "Fúria Titânica",
    "arquivo": "../cards/Fúria_Titânica.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Ganha +8 de Combate neste turno. Fim do turno sofre debuff permanente de -4 de Resistência.",
    "custoHabilidade": null
  },
  {
    "nome": "Troca Equivalente",
    "arquivo": "../cards/Troca_Equivalente.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 1,
    "resistencia": null,
    "combate": null,
    "efeito": "Embaralhe até 3 cartas da mão no baralho. Compre a mesma quantidade.",
    "custoHabilidade": null
  },
  {
    "nome": "Exílio Dimensional",
    "arquivo": "../cards/Exílio_Dimensional.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 5,
    "resistencia": null,
    "combate": null,
    "efeito": "Envie o combatente ativo inimigo direto para a Pilha de Descarte. O oponente invoca outro de graça.",
    "custoHabilidade": null
  },
  {
    "nome": "Chamado do Além",
    "arquivo": "../cards/Chamado_do_Além.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Escolha uma carta de Maldição/Equipamento da Pilha de Descarte e coloque em jogo sem pagar custo.",
    "custoHabilidade": null
  },
  {
    "nome": "Purificação Arcana",
    "arquivo": "../cards/Purificação_Arcana.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Revele todas as Maldições do oponente. Destrua duas delas.",
    "custoHabilidade": null
  },
  {
    "nome": "Manto da Natureza",
    "arquivo": "../cards/Manto_da_Natureza.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "O combatente ganha +5 de Resistência e imunidade a Habilidades de Mana inimigas.",
    "custoHabilidade": null
  },
  {
    "nome": "Escudo de Gelo Absoluto",
    "arquivo": "../cards/Escudo_de_Gelo_Absoluto.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "O ataque é completamente anulado e o combatente inimigo perde seu elemento até o fim do turno.",
    "custoHabilidade": null
  },
  {
    "nome": "Espelho das Ilusões",
    "arquivo": "../cards/Espelho_das_Ilusões.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "O seu combatente não sofre dano. O dano volta integralmente para a Resistência do atacante.",
    "custoHabilidade": null
  },
  {
    "nome": "Areias Movediças",
    "arquivo": "../cards/Areias_Movediças.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "O combatente invocado entra em campo com -5 de Resistência permanente.",
    "custoHabilidade": null
  },
  {
    "nome": "Roubo de Essência",
    "arquivo": "../cards/Roubo_de_Essência.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Cancele a Habilidade de Mana inimiga e roube a Mana gasta para você.",
    "custoHabilidade": null
  },
  {
    "nome": "Praga da Ferrugem",
    "arquivo": "../cards/Praga_da_Ferrugem.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 1,
    "resistencia": null,
    "combate": null,
    "efeito": "O equipamento jogado é destruído antes do efeito. Inimigo perde 1 de Mana.",
    "custoHabilidade": null
  },
  {
    "nome": "Vínculo Sombrio",
    "arquivo": "../cards/Vínculo_Sombrio.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "O Combate do combatente inimigo é reduzido para exatamente 10 até o fim do turno.",
    "custoHabilidade": null
  },
  {
    "nome": "Nevoeiro do Pânico",
    "arquivo": "../cards/Nevoeiro_do_Pânico.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Oponente descarta a carta recém comprada no turno e compra a do fundo do baralho.",
    "custoHabilidade": null
  },
  {
    "nome": "Barreira de Vento Cortante",
    "arquivo": "../cards/Barreira_de_Vento_Cortante.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "O ataque é negado e o atacante retorna ao Panteão.",
    "custoHabilidade": null
  },
  {
    "nome": "Retribuição Kármica",
    "arquivo": "../cards/Retribuição_Kármica.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 4,
    "resistencia": null,
    "combate": null,
    "efeito": "Você não sofre dano, reflete tudo para a Resistência do inimigo.",
    "custoHabilidade": null
  },
  {
    "nome": "Aperto da Múmia",
    "arquivo": "../cards/Aperto_da_Múmia.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Inimigo entra sofrendo -5 de Resistência e -3 de Combate.",
    "custoHabilidade": null
  },
  {
    "nome": "Mente Fraturada",
    "arquivo": "../cards/Mente_Fraturada.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Inimigo descarta a carta de maior custo ao tentar comprar cartas extras.",
    "custoHabilidade": null
  },
  {
    "nome": "Amnésia Mágica",
    "arquivo": "../cards/Amnésia_Mágica.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "A Habilidade de Mana falha e o combatente perde o direito de usar habilidades.",
    "custoHabilidade": null
  },
  {
    "nome": "Fio do Destino Cortado",
    "arquivo": "../cards/Fio_do_Destino_Cortado.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 2,
    "resistencia": null,
    "combate": null,
    "efeito": "Inverte o buff ativado pelo inimigo (ex: +4 vira -4).",
    "custoHabilidade": null
  },
  {
    "nome": "Rebote Arcano",
    "arquivo": "../cards/Rebote_Arcano.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Redireciona feitiço inimigo para o combatente dele próprio.",
    "custoHabilidade": null
  },
  {
    "nome": "Caixa de Pandora",
    "arquivo": "../cards/Caixa_de_Pandora.png",
    "tipo": "Maldição",
    "elemento": null,
    "custoMana": 1,
    "resistencia": null,
    "combate": null,
    "efeito": "Ao ter Domínio/Combatente destruído, força inimigo a descartar 3 cartas do topo do baralho.",
    "custoHabilidade": null
  },
  {
    "nome": "Apoio Incondicional",
    "arquivo": "../cards/Apoio_Incondicional.png",
    "tipo": "Encantamento",
    "elemento": null,
    "custoMana": 3,
    "resistencia": null,
    "combate": null,
    "efeito": "Escolha o seu Combatente em campo e 1 no Panteão. Se um deles for alvo de um ataque ou de um efeito de carta do oponente, você pode dividir o dano da batalha igualmente entre os dois. ",
    "custoHabilidade": null
  }
];
